#! /bin/bash
pkg="cert-generator"
version="0.1"

parent_file_path="/etc/kubernetes/ssl/"

DOMAIN=$1

set -o nounset
set -o pipefail

function _chmod {
  CN=$1
  chmod 0644 $CN.pem ${CN}-key.pem ${CN}-config.json
}

function generate {
  CN=$1
  PROFILE=$2
  HOSTS=$3

  echo "$(csr $CN)" \
    | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=$PROFILE \
      -hostname="$HOSTS" - \
    | cfssljson -bare $CN

  _chmod $CN
}

cd $parent_file_path

# Decrypt the CA files on disk
aws kms decrypt --ciphertext-blob fileb://$parent_file_path/ca.encrypted.pem --output text --query Plaintext | base64 --decode > ca.pem
aws kms decrypt --ciphertext-blob fileb://$parent_file_path/ca-key.encrypted.pem --output text --query Plaintext | base64 --decode > ca-key.pem
aws kms decrypt --ciphertext-blob fileb://$parent_file_path/ca-config.encrypted.json --output text --query Plaintext | base64 --decode > ca-config.json
_chmod ca

# generate keys and certs
generate assets client-server "$DOMAIN"

exit 0
